// Package theme verifies Codex Skin data-only theme packages and descriptors.
package theme

import (
	"archive/zip"
	"bytes"
	"crypto/ed25519"
	"crypto/sha256"
	_ "embed"
	"encoding/base64"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"hash/crc32"
	"image/jpeg"
	"io"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

const (
	SchemaVersion       = 1
	DescriptorVersion   = 1
	MaxManifestBytes    = 256 * 1024
	MaxPackageBytes     = 25 * 1024 * 1024
	MaxExpandedBytes    = 60 * 1024 * 1024
	MaxAssetBytes       = 15 * 1024 * 1024
	MaxFileCount        = 50
	MaxImageEdge        = 8192
	MaxImagePixels      = 50_000_000
	signatureDomainText = "codex-skin/theme-release-descriptor/v1\x00"
)

var (
	ErrManifestInvalid     = errors.New("theme manifest is invalid")
	ErrManifestCanonical   = errors.New("theme manifest is not canonical")
	ErrDescriptorInvalid   = errors.New("theme release descriptor is invalid")
	ErrDescriptorCanonical = errors.New("theme release descriptor is not canonical")
	ErrKeysetCanonical     = errors.New("theme verification keyset is not canonical")
	ErrSignatureInvalid    = errors.New("theme release signature is invalid")
	ErrSigningKeyInvalid   = errors.New("theme signing key is invalid")
	ErrEngineIncompatible  = errors.New("theme requires a newer engine")
	ErrPackageInvalid      = errors.New("theme package is invalid")
	ErrPackageMismatch     = errors.New("theme package does not match descriptor")
	ErrUnsafePath          = errors.New("theme package path is unsafe")
)

// trustedKeysetRaw is generated byte-for-byte from the canonical Private
// contract export. It is the immutable theme-release trust anchor compiled
// into the Helper.
//
//go:embed trusted-verification-keys-v1.json
var trustedKeysetRaw []byte

var (
	semverPattern = regexp.MustCompile(`^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:-((?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*))?$`)
	publicID      = regexp.MustCompile(`^[0-9]{6}$`)
	keyID         = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{2,63}$`)
	digest        = regexp.MustCompile(`^[0-9a-f]{64}$`)
	color         = regexp.MustCompile(`^#[0-9A-F]{6}(?:[0-9A-F]{2})?$`)
	assetPath     = regexp.MustCompile(`^assets/[0-9a-f]{64}\.(png|jpg|webp)$`)
)

type Tokens struct {
	BackgroundImage   string  `json:"backgroundImage"`
	BackgroundOverlay float64 `json:"backgroundOverlay"`
	SurfaceOpacity    float64 `json:"surfaceOpacity"`
	SurfaceBlurPx     int     `json:"surfaceBlurPx"`
	TextPrimary       string  `json:"textPrimary"`
	TextSecondary     string  `json:"textSecondary"`
	Accent            string  `json:"accent"`
	Border            string  `json:"border"`
	RadiusScale       float64 `json:"radiusScale"`
}

type Regions struct {
	Home            bool `json:"home"`
	Sidebar         bool `json:"sidebar"`
	SuggestionCards bool `json:"suggestionCards"`
	ProjectPicker   bool `json:"projectPicker"`
	Composer        bool `json:"composer"`
}

type Design struct {
	Mode    string  `json:"mode"`
	Tokens  Tokens  `json:"tokens"`
	Regions Regions `json:"regions"`
}

type Customization struct {
	Allowed []string `json:"allowed"`
}

type Asset struct {
	Path        string `json:"path"`
	Role        string `json:"role"`
	ContentType string `json:"contentType"`
	ByteSize    int64  `json:"byteSize"`
	SHA256      string `json:"sha256"`
}

type Compatibility struct {
	Platforms        []string `json:"platforms"`
	MinEngineVersion string   `json:"minEngineVersion"`
}

type Manifest struct {
	SchemaVersion int           `json:"schemaVersion"`
	ThemePublicID string        `json:"themePublicId"`
	ThemeVersion  string        `json:"themeVersion"`
	Name          string        `json:"name"`
	Design        Design        `json:"design"`
	Customization Customization `json:"customization"`
	Assets        []Asset       `json:"assets"`
	Compatibility Compatibility `json:"compatibility"`
}

type Descriptor struct {
	DescriptorVersion int    `json:"descriptorVersion"`
	ThemePublicID     string `json:"themePublicId"`
	ThemeVersion      string `json:"themeVersion"`
	SchemaVersion     int    `json:"schemaVersion"`
	ManifestSHA256    string `json:"manifestSha256"`
	PackageSHA256     string `json:"packageSha256"`
	PackageByteSize   int64  `json:"packageByteSize"`
	PublishedAt       string `json:"publishedAt"`
	SigningKeyID      string `json:"signingKeyId"`
}

type VerificationKey struct {
	KeyID           string `json:"keyId"`
	Algorithm       string `json:"algorithm"`
	Usage           string `json:"usage"`
	PublicKeyBase64 string `json:"publicKeyBase64"`
	NotBefore       string `json:"notBefore"`
	NotAfter        string `json:"notAfter"`
	Status          string `json:"status"`
}

type VerificationKeyset struct {
	SchemaVersion int               `json:"schemaVersion"`
	Keys          []VerificationKey `json:"keys"`
}

type Verified struct {
	Manifest        Manifest
	ManifestBytes   []byte
	Descriptor      Descriptor
	DescriptorBytes []byte
	Signature       []byte
	KeysetBytes     []byte
	PackagePath     string
	PackageSHA256   string
	PackageByteSize int64
	packageBytes    []byte
}

func canonicalBytes(value any) ([]byte, error) {
	content, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	return append(content, '\n'), nil
}

func canonicalIndentedBytes(value any) ([]byte, error) {
	content, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(content, '\n'), nil
}

func rejectDuplicateJSON(raw []byte, label string) error {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.UseNumber()
	if err := scanJSONValue(decoder, label); err != nil {
		return err
	}
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err == nil {
			return fmt.Errorf("%s contains multiple JSON values", label)
		}
		return fmt.Errorf("%s contains trailing JSON: %w", label, err)
	}
	return nil
}

func scanJSONValue(decoder *json.Decoder, label string) error {
	token, err := decoder.Token()
	if err != nil {
		return fmt.Errorf("%s is invalid JSON: %w", label, err)
	}
	delim, ok := token.(json.Delim)
	if !ok {
		return nil
	}
	switch delim {
	case '{':
		keys := map[string]struct{}{}
		for decoder.More() {
			keyToken, err := decoder.Token()
			if err != nil {
				return fmt.Errorf("%s has invalid object key: %w", label, err)
			}
			key, ok := keyToken.(string)
			if !ok {
				return fmt.Errorf("%s has a non-string object key", label)
			}
			if _, exists := keys[key]; exists {
				return fmt.Errorf("%s contains duplicate JSON key %q", label, key)
			}
			keys[key] = struct{}{}
			if err := scanJSONValue(decoder, label); err != nil {
				return err
			}
		}
		end, err := decoder.Token()
		if err != nil || end != json.Delim('}') {
			return fmt.Errorf("%s has an unterminated object", label)
		}
	case '[':
		for decoder.More() {
			if err := scanJSONValue(decoder, label); err != nil {
				return err
			}
		}
		end, err := decoder.Token()
		if err != nil || end != json.Delim(']') {
			return fmt.Errorf("%s has an unterminated array", label)
		}
	default:
		return fmt.Errorf("%s contains unexpected JSON delimiter", label)
	}
	return nil
}

func decodeStrict(raw []byte, label string, target any) error {
	if err := rejectDuplicateJSON(raw, label); err != nil {
		return err
	}
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		return fmt.Errorf("%s decode failed: %w", label, err)
	}
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		return fmt.Errorf("%s contains trailing data", label)
	}
	return nil
}

func ParseManifest(raw []byte) (Manifest, error) {
	if len(raw) < 1 || len(raw) > MaxManifestBytes {
		return Manifest{}, fmt.Errorf("%w: byte length", ErrManifestInvalid)
	}
	var manifest Manifest
	if err := decodeStrict(raw, "manifest", &manifest); err != nil {
		return Manifest{}, fmt.Errorf("%w: %v", ErrManifestInvalid, err)
	}
	if err := validateManifest(manifest); err != nil {
		return Manifest{}, err
	}
	canonical, err := canonicalBytes(manifest)
	if err != nil {
		return Manifest{}, fmt.Errorf("%w: canonicalize: %v", ErrManifestInvalid, err)
	}
	if !bytes.Equal(raw, canonical) {
		return Manifest{}, ErrManifestCanonical
	}
	return manifest, nil
}

func validateManifest(manifest Manifest) error {
	if manifest.SchemaVersion != SchemaVersion ||
		!publicID.MatchString(manifest.ThemePublicID) ||
		!semverPattern.MatchString(manifest.ThemeVersion) ||
		len(manifest.ThemeVersion) > 64 ||
		len(manifest.Name) < 1 ||
		len(manifest.Name) > 80 {
		return fmt.Errorf("%w: identity fields", ErrManifestInvalid)
	}
	if manifest.Design.Mode != "light" && manifest.Design.Mode != "dark" {
		return fmt.Errorf("%w: design mode", ErrManifestInvalid)
	}
	tokens := manifest.Design.Tokens
	if !assetPath.MatchString(tokens.BackgroundImage) ||
		tokens.BackgroundOverlay < 0 || tokens.BackgroundOverlay > 0.85 ||
		tokens.SurfaceOpacity < 0.55 || tokens.SurfaceOpacity > 1 ||
		tokens.SurfaceBlurPx < 0 || tokens.SurfaceBlurPx > 40 ||
		!color.MatchString(tokens.TextPrimary) ||
		!color.MatchString(tokens.TextSecondary) ||
		!color.MatchString(tokens.Accent) ||
		!color.MatchString(tokens.Border) ||
		tokens.RadiusScale < 0.5 || tokens.RadiusScale > 1.5 {
		return fmt.Errorf("%w: design tokens", ErrManifestInvalid)
	}
	regions := manifest.Design.Regions
	if !regions.Home || !regions.Sidebar || !regions.SuggestionCards || !regions.ProjectPicker || !regions.Composer {
		return fmt.Errorf("%w: all five regions are required", ErrManifestInvalid)
	}
	allowedNames := map[string]bool{
		"backgroundOverlay": true,
		"surfaceOpacity":    true,
		"surfaceBlurPx":     true,
		"accent":            true,
		"radiusScale":       true,
	}
	if len(manifest.Customization.Allowed) > len(allowedNames) {
		return fmt.Errorf("%w: customization count", ErrManifestInvalid)
	}
	seenCustom := map[string]bool{}
	for _, name := range manifest.Customization.Allowed {
		if !allowedNames[name] || seenCustom[name] {
			return fmt.Errorf("%w: customization field", ErrManifestInvalid)
		}
		seenCustom[name] = true
	}
	if len(manifest.Assets) < 1 || len(manifest.Assets) > 10 {
		return fmt.Errorf("%w: asset count", ErrManifestInvalid)
	}
	seenAssets := map[string]bool{}
	backgrounds := 0
	for _, asset := range manifest.Assets {
		if seenAssets[asset.Path] ||
			!assetPath.MatchString(asset.Path) ||
			!digest.MatchString(asset.SHA256) ||
			!strings.Contains(asset.Path, asset.SHA256) ||
			asset.ByteSize < 1 ||
			asset.ByteSize > MaxAssetBytes {
			return fmt.Errorf("%w: asset identity", ErrManifestInvalid)
		}
		seenAssets[asset.Path] = true
		if asset.Role != "background" && asset.Role != "overlay" {
			return fmt.Errorf("%w: asset role", ErrManifestInvalid)
		}
		if asset.ContentType != "image/png" &&
			asset.ContentType != "image/jpeg" &&
			asset.ContentType != "image/webp" {
			return fmt.Errorf("%w: asset content type", ErrManifestInvalid)
		}
		if !strings.HasSuffix(asset.Path, extensionForContentType(asset.ContentType)) {
			return fmt.Errorf("%w: asset extension", ErrManifestInvalid)
		}
		if asset.Role == "background" {
			backgrounds++
			if asset.Path != tokens.BackgroundImage {
				return fmt.Errorf("%w: background path mismatch", ErrManifestInvalid)
			}
		}
	}
	if backgrounds != 1 {
		return fmt.Errorf("%w: exactly one background is required", ErrManifestInvalid)
	}
	if len(manifest.Compatibility.Platforms) != 2 ||
		manifest.Compatibility.Platforms[0] != "macos" ||
		manifest.Compatibility.Platforms[1] != "windows" ||
		!semverPattern.MatchString(manifest.Compatibility.MinEngineVersion) ||
		len(manifest.Compatibility.MinEngineVersion) > 64 {
		return fmt.Errorf("%w: compatibility", ErrManifestInvalid)
	}
	return nil
}

func ParseDescriptor(raw []byte) (Descriptor, error) {
	if len(raw) < 1 || len(raw) > 64*1024 {
		return Descriptor{}, fmt.Errorf("%w: byte length", ErrDescriptorInvalid)
	}
	var descriptor Descriptor
	if err := decodeStrict(raw, "descriptor", &descriptor); err != nil {
		return Descriptor{}, fmt.Errorf("%w: %v", ErrDescriptorInvalid, err)
	}
	if err := validateDescriptor(descriptor); err != nil {
		return Descriptor{}, err
	}
	canonical, err := canonicalBytes(descriptor)
	if err != nil {
		return Descriptor{}, fmt.Errorf("%w: canonicalize: %v", ErrDescriptorInvalid, err)
	}
	if !bytes.Equal(raw, canonical) {
		return Descriptor{}, ErrDescriptorCanonical
	}
	return descriptor, nil
}

func validateDescriptor(descriptor Descriptor) error {
	if descriptor.DescriptorVersion != DescriptorVersion ||
		descriptor.SchemaVersion != SchemaVersion ||
		!publicID.MatchString(descriptor.ThemePublicID) ||
		!semverPattern.MatchString(descriptor.ThemeVersion) ||
		len(descriptor.ThemeVersion) > 64 ||
		!digest.MatchString(descriptor.ManifestSHA256) ||
		!digest.MatchString(descriptor.PackageSHA256) ||
		descriptor.PackageByteSize < 1 ||
		descriptor.PackageByteSize > MaxPackageBytes ||
		!keyID.MatchString(descriptor.SigningKeyID) {
		return fmt.Errorf("%w: fields", ErrDescriptorInvalid)
	}
	parsed, err := time.Parse(time.RFC3339Nano, descriptor.PublishedAt)
	if err != nil ||
		!strings.HasSuffix(descriptor.PublishedAt, "Z") ||
		parsed.Location() != time.UTC {
		return fmt.Errorf("%w: publishedAt", ErrDescriptorInvalid)
	}
	return nil
}

func ParseKeyset(raw []byte) (VerificationKeyset, error) {
	if len(raw) < 1 || len(raw) > 64*1024 {
		return VerificationKeyset{}, fmt.Errorf("%w: byte length", ErrSigningKeyInvalid)
	}
	var keyset VerificationKeyset
	if err := decodeStrict(raw, "keyset", &keyset); err != nil {
		return VerificationKeyset{}, fmt.Errorf("%w: %v", ErrSigningKeyInvalid, err)
	}
	if keyset.SchemaVersion != 1 || len(keyset.Keys) < 1 || len(keyset.Keys) > 8 {
		return VerificationKeyset{}, fmt.Errorf("%w: schema or key count", ErrSigningKeyInvalid)
	}
	seen := map[string]bool{}
	for _, key := range keyset.Keys {
		rawKey, err := base64.StdEncoding.Strict().DecodeString(key.PublicKeyBase64)
		notBefore, beforeErr := time.Parse(time.RFC3339Nano, key.NotBefore)
		notAfter, afterErr := time.Parse(time.RFC3339Nano, key.NotAfter)
		if seen[key.KeyID] ||
			!keyID.MatchString(key.KeyID) ||
			key.Algorithm != "Ed25519" ||
			key.Usage != "theme-release" ||
			err != nil ||
			len(rawKey) != ed25519.PublicKeySize ||
			beforeErr != nil ||
			afterErr != nil ||
			!strings.HasSuffix(key.NotBefore, "Z") ||
			!strings.HasSuffix(key.NotAfter, "Z") ||
			notBefore.Location() != time.UTC ||
			notAfter.Location() != time.UTC ||
			!notBefore.Before(notAfter) ||
			(key.Status != "active" && key.Status != "verify-only" && key.Status != "revoked") {
			return VerificationKeyset{}, fmt.Errorf("%w: key entry", ErrSigningKeyInvalid)
		}
		seen[key.KeyID] = true
	}
	canonical, err := canonicalIndentedBytes(keyset)
	if err != nil {
		return VerificationKeyset{}, fmt.Errorf("%w: canonicalize: %v", ErrSigningKeyInvalid, err)
	}
	if !bytes.Equal(raw, canonical) {
		return VerificationKeyset{}, ErrKeysetCanonical
	}
	return keyset, nil
}

// EngineCompatible applies SemVer precedence to the signed minimum engine
// version. Invalid versions always fail closed.
func EngineCompatible(current, minimum string) bool {
	return compareSemver(current, minimum) >= 0
}

func compareSemver(left, right string) int {
	leftMatch := semverPattern.FindStringSubmatch(left)
	rightMatch := semverPattern.FindStringSubmatch(right)
	if leftMatch == nil || rightMatch == nil {
		return -1
	}
	for index := 1; index <= 3; index++ {
		if compared := compareNumericIdentifier(leftMatch[index], rightMatch[index]); compared != 0 {
			return compared
		}
	}
	leftPre, rightPre := leftMatch[4], rightMatch[4]
	if leftPre == "" && rightPre == "" {
		return 0
	}
	if leftPre == "" {
		return 1
	}
	if rightPre == "" {
		return -1
	}
	leftParts, rightParts := strings.Split(leftPre, "."), strings.Split(rightPre, ".")
	for index := 0; index < len(leftParts) && index < len(rightParts); index++ {
		leftNumeric := isNumericIdentifier(leftParts[index])
		rightNumeric := isNumericIdentifier(rightParts[index])
		switch {
		case leftNumeric && rightNumeric:
			if compared := compareNumericIdentifier(leftParts[index], rightParts[index]); compared != 0 {
				return compared
			}
		case leftNumeric:
			return -1
		case rightNumeric:
			return 1
		case leftParts[index] < rightParts[index]:
			return -1
		case leftParts[index] > rightParts[index]:
			return 1
		}
	}
	switch {
	case len(leftParts) < len(rightParts):
		return -1
	case len(leftParts) > len(rightParts):
		return 1
	default:
		return 0
	}
}

func compareNumericIdentifier(left, right string) int {
	switch {
	case len(left) < len(right):
		return -1
	case len(left) > len(right):
		return 1
	case left < right:
		return -1
	case left > right:
		return 1
	default:
		return 0
	}
}

func isNumericIdentifier(value string) bool {
	if value == "" {
		return false
	}
	for _, character := range value {
		if character < '0' || character > '9' {
			return false
		}
	}
	return true
}

func verifySignature(descriptor Descriptor, descriptorRaw, signatureRaw, keysetRaw []byte) ([]byte, error) {
	keyset, err := ParseKeyset(keysetRaw)
	if err != nil {
		return nil, err
	}
	signatureText := strings.TrimSuffix(string(signatureRaw), "\n")
	if strings.ContainsAny(signatureText, "\r\t ") || signatureText == string(signatureRaw) {
		return nil, fmt.Errorf("%w: signature file must be one base64 line", ErrSignatureInvalid)
	}
	signature, err := base64.StdEncoding.Strict().DecodeString(signatureText)
	if err != nil || len(signature) != ed25519.SignatureSize {
		return nil, fmt.Errorf("%w: encoding", ErrSignatureInvalid)
	}
	publishedAt, _ := time.Parse(time.RFC3339Nano, descriptor.PublishedAt)
	for _, key := range keyset.Keys {
		if key.KeyID != descriptor.SigningKeyID {
			continue
		}
		if key.Status == "revoked" {
			return nil, fmt.Errorf("%w: key is revoked", ErrSigningKeyInvalid)
		}
		notBefore, _ := time.Parse(time.RFC3339Nano, key.NotBefore)
		notAfter, _ := time.Parse(time.RFC3339Nano, key.NotAfter)
		if publishedAt.Before(notBefore) || !publishedAt.Before(notAfter) {
			return nil, fmt.Errorf("%w: descriptor outside key validity", ErrSigningKeyInvalid)
		}
		rawKey, _ := base64.StdEncoding.Strict().DecodeString(key.PublicKeyBase64)
		message := append([]byte(signatureDomainText), descriptorRaw...)
		if !ed25519.Verify(ed25519.PublicKey(rawKey), message, signature) {
			return nil, ErrSignatureInvalid
		}
		return signature, nil
	}
	return nil, fmt.Errorf("%w: unknown key id", ErrSigningKeyInvalid)
}

func readPackageFile(packagePath string) ([]byte, string, int64, error) {
	info, err := os.Lstat(packagePath)
	if err != nil {
		return nil, "", 0, fmt.Errorf("%w: inspect: %v", ErrPackageInvalid, err)
	}
	if !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 || info.Size() < 1 || info.Size() > MaxPackageBytes {
		return nil, "", 0, fmt.Errorf("%w: file shape or size", ErrPackageInvalid)
	}
	file, err := os.Open(packagePath)
	if err != nil {
		return nil, "", 0, fmt.Errorf("%w: open: %v", ErrPackageInvalid, err)
	}
	defer file.Close()
	content, err := io.ReadAll(io.LimitReader(file, MaxPackageBytes+1))
	if err != nil || int64(len(content)) != info.Size() {
		return nil, "", 0, fmt.Errorf("%w: read", ErrPackageInvalid)
	}
	return content, sha256Hex(content), int64(len(content)), nil
}

func readArchive(packageBytes []byte) (Manifest, []byte, error) {
	archive, err := zip.NewReader(bytes.NewReader(packageBytes), int64(len(packageBytes)))
	if err != nil {
		return Manifest{}, nil, fmt.Errorf("%w: zip: %v", ErrPackageInvalid, err)
	}
	if len(archive.File) < 2 || len(archive.File) > MaxFileCount {
		return Manifest{}, nil, fmt.Errorf("%w: entry count", ErrPackageInvalid)
	}
	seen := map[string]bool{}
	var expanded uint64
	var manifestRaw []byte
	var manifest Manifest
	previousName := ""
	for index, entry := range archive.File {
		name := entry.Name
		clean := path.Clean(name)
		if seen[name] ||
			entry.NonUTF8 ||
			name != clean ||
			name == "." ||
			strings.HasPrefix(name, "/") ||
			strings.Contains(name, "\\") ||
			(index == 0 && name != "manifest.json") ||
			(index > 0 && !assetPath.MatchString(name)) ||
			(index > 1 && name <= previousName) ||
			len(entry.Extra) != 0 ||
			entry.Comment != "" ||
			entry.Method != zip.Store ||
			!entry.Mode().IsRegular() ||
			entry.Mode()&os.ModeSymlink != 0 {
			return Manifest{}, nil, fmt.Errorf("%w: unsafe or non-canonical entry %q", ErrPackageInvalid, name)
		}
		seen[name] = true
		previousName = name
		expanded += entry.UncompressedSize64
		limit := uint64(MaxAssetBytes)
		if name == "manifest.json" {
			limit = MaxManifestBytes
		}
		if entry.UncompressedSize64 < 1 ||
			entry.UncompressedSize64 > limit ||
			entry.CompressedSize64 != entry.UncompressedSize64 ||
			expanded > MaxExpandedBytes {
			return Manifest{}, nil, fmt.Errorf("%w: entry size", ErrPackageInvalid)
		}
		reader, err := entry.Open()
		if err != nil {
			return Manifest{}, nil, fmt.Errorf("%w: open entry: %v", ErrPackageInvalid, err)
		}
		content, readErr := io.ReadAll(io.LimitReader(reader, int64(limit)+1))
		closeErr := reader.Close()
		if readErr != nil || closeErr != nil || uint64(len(content)) != entry.UncompressedSize64 {
			return Manifest{}, nil, fmt.Errorf("%w: read entry", ErrPackageInvalid)
		}
		if name == "manifest.json" {
			manifestRaw = content
			manifest, err = ParseManifest(content)
			if err != nil {
				return Manifest{}, nil, err
			}
		}
	}
	if manifestRaw == nil {
		return Manifest{}, nil, fmt.Errorf("%w: missing manifest", ErrPackageInvalid)
	}
	if len(seen) != 1+len(manifest.Assets) {
		return Manifest{}, nil, fmt.Errorf("%w: undeclared or missing asset", ErrPackageInvalid)
	}
	for _, asset := range manifest.Assets {
		entry, err := archive.Open(asset.Path)
		if err != nil {
			return Manifest{}, nil, fmt.Errorf("%w: missing asset", ErrPackageInvalid)
		}
		content, readErr := io.ReadAll(io.LimitReader(entry, MaxAssetBytes+1))
		closeErr := entry.Close()
		if readErr != nil || closeErr != nil ||
			int64(len(content)) != asset.ByteSize ||
			sha256Hex(content) != asset.SHA256 ||
			!matchesImageTypeAndDimensions(content, asset.ContentType) {
			return Manifest{}, nil, fmt.Errorf("%w: asset mismatch %q", ErrPackageInvalid, asset.Path)
		}
	}
	return manifest, manifestRaw, nil
}

func sha256Hex(content []byte) string {
	sum := sha256.Sum256(content)
	return hex.EncodeToString(sum[:])
}

func matchesImageTypeAndDimensions(content []byte, contentType string) bool {
	switch contentType {
	case "image/png":
		width, height, ok := pngDimensionsAndChecksums(content)
		return ok && validDimensions(width, height)
	case "image/jpeg":
		config, err := jpeg.DecodeConfig(bytes.NewReader(content))
		return err == nil && validDimensions(uint64(config.Width), uint64(config.Height))
	case "image/webp":
		width, height, ok := webpDimensions(content)
		return ok && validDimensions(width, height)
	default:
		return false
	}
}

func extensionForContentType(contentType string) string {
	switch contentType {
	case "image/png":
		return ".png"
	case "image/jpeg":
		return ".jpg"
	case "image/webp":
		return ".webp"
	default:
		return ""
	}
}

func validDimensions(width, height uint64) bool {
	return width >= 1 &&
		height >= 1 &&
		width <= MaxImageEdge &&
		height <= MaxImageEdge &&
		width*height <= MaxImagePixels
}

func pngDimensionsAndChecksums(content []byte) (uint64, uint64, bool) {
	const headerBytes = 12
	if len(content) < 33 || !bytes.Equal(content[:8], []byte{137, 80, 78, 71, 13, 10, 26, 10}) {
		return 0, 0, false
	}
	offset := 8
	seenIHDR := false
	seenIDAT := false
	for offset+headerBytes <= len(content) {
		length := uint64(binary.BigEndian.Uint32(content[offset : offset+4]))
		chunkEnd := uint64(offset) + headerBytes + length
		if length > MaxAssetBytes || chunkEnd > uint64(len(content)) {
			return 0, 0, false
		}
		chunkType := content[offset+4 : offset+8]
		dataEnd := offset + 8 + int(length)
		expectedCRC := binary.BigEndian.Uint32(content[dataEnd : dataEnd+4])
		if crc32.ChecksumIEEE(content[offset+4:dataEnd]) != expectedCRC {
			return 0, 0, false
		}
		switch string(chunkType) {
		case "IHDR":
			if seenIHDR || offset != 8 || length != 13 {
				return 0, 0, false
			}
			seenIHDR = true
		case "IDAT":
			if !seenIHDR {
				return 0, 0, false
			}
			seenIDAT = true
		case "IEND":
			if !seenIHDR || !seenIDAT || length != 0 || chunkEnd != uint64(len(content)) {
				return 0, 0, false
			}
			return uint64(binary.BigEndian.Uint32(content[16:20])), uint64(binary.BigEndian.Uint32(content[20:24])), true
		}
		offset = int(chunkEnd)
	}
	return 0, 0, false
}

func webpDimensions(content []byte) (uint64, uint64, bool) {
	if len(content) < 30 ||
		string(content[:4]) != "RIFF" ||
		uint64(binary.LittleEndian.Uint32(content[4:8]))+8 != uint64(len(content)) ||
		string(content[8:12]) != "WEBP" {
		return 0, 0, false
	}
	chunkSize := uint64(binary.LittleEndian.Uint32(content[16:20]))
	if chunkSize+20 > uint64(len(content)) {
		return 0, 0, false
	}
	switch string(content[12:16]) {
	case "VP8X":
		if chunkSize < 10 {
			return 0, 0, false
		}
		width := uint64(content[24]) | uint64(content[25])<<8 | uint64(content[26])<<16
		height := uint64(content[27]) | uint64(content[28])<<8 | uint64(content[29])<<16
		return width + 1, height + 1, true
	case "VP8 ":
		if chunkSize < 10 || !bytes.Equal(content[23:26], []byte{0x9d, 0x01, 0x2a}) {
			return 0, 0, false
		}
		width := uint64(binary.LittleEndian.Uint16(content[26:28]) & 0x3fff)
		height := uint64(binary.LittleEndian.Uint16(content[28:30]) & 0x3fff)
		return width, height, true
	case "VP8L":
		if chunkSize < 5 || content[20] != 0x2f {
			return 0, 0, false
		}
		bits := binary.LittleEndian.Uint32(content[21:25])
		width := uint64(bits&0x3fff) + 1
		height := uint64((bits>>14)&0x3fff) + 1
		return width, height, true
	default:
		return 0, 0, false
	}
}

// Verify validates a theme exclusively against the immutable keyset embedded
// in this Helper. Callers cannot replace the signing trust root.
func Verify(packagePath string, descriptorRaw, signatureRaw []byte) (Verified, error) {
	return verifyWithKeyset(packagePath, descriptorRaw, signatureRaw, trustedKeysetRaw)
}

func verifyWithKeyset(packagePath string, descriptorRaw, signatureRaw, keysetRaw []byte) (Verified, error) {
	descriptor, err := ParseDescriptor(descriptorRaw)
	if err != nil {
		return Verified{}, err
	}
	signature, err := verifySignature(descriptor, descriptorRaw, signatureRaw, keysetRaw)
	if err != nil {
		return Verified{}, err
	}
	packageBytes, packageDigest, packageSize, err := readPackageFile(packagePath)
	if err != nil {
		return Verified{}, err
	}
	if packageSize != descriptor.PackageByteSize || packageDigest != descriptor.PackageSHA256 {
		return Verified{}, ErrPackageMismatch
	}
	manifest, manifestRaw, err := readArchive(packageBytes)
	if err != nil {
		return Verified{}, err
	}
	if sha256Hex(manifestRaw) != descriptor.ManifestSHA256 ||
		manifest.ThemePublicID != descriptor.ThemePublicID ||
		manifest.ThemeVersion != descriptor.ThemeVersion ||
		manifest.SchemaVersion != descriptor.SchemaVersion {
		return Verified{}, ErrPackageMismatch
	}
	return Verified{
		Manifest:        manifest,
		ManifestBytes:   manifestRaw,
		Descriptor:      descriptor,
		DescriptorBytes: append([]byte(nil), descriptorRaw...),
		Signature:       signature,
		KeysetBytes:     append([]byte(nil), keysetRaw...),
		PackagePath:     packagePath,
		PackageSHA256:   packageDigest,
		PackageByteSize: packageSize,
		packageBytes:    packageBytes,
	}, nil
}

// WriteVerificationBundle persists the exact bytes needed to revalidate a
// previously verified package without network access.
func WriteVerificationBundle(verified Verified, destination string) error {
	if len(verified.packageBytes) < 1 ||
		int64(len(verified.packageBytes)) != verified.PackageByteSize ||
		sha256Hex(verified.packageBytes) != verified.PackageSHA256 ||
		len(verified.DescriptorBytes) < 1 ||
		len(verified.Signature) != ed25519.SignatureSize ||
		len(verified.KeysetBytes) < 1 {
		return fmt.Errorf("%w: incomplete verification bundle", ErrPackageInvalid)
	}
	files := []struct {
		name    string
		content []byte
	}{
		{name: "package.cskin", content: verified.packageBytes},
		{name: "release-descriptor.json", content: verified.DescriptorBytes},
		{name: "release-descriptor.sig", content: []byte(base64.StdEncoding.EncodeToString(verified.Signature) + "\n")},
		{name: "verification-keyset.json", content: verified.KeysetBytes},
	}
	for _, item := range files {
		target := filepath.Join(destination, item.name)
		if err := ensureContained(destination, target); err != nil {
			return err
		}
		file, err := os.OpenFile(target, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o600)
		if err != nil {
			return fmt.Errorf("%w: create verification bundle: %v", ErrUnsafePath, err)
		}
		_, writeErr := file.Write(item.content)
		syncErr := file.Sync()
		closeErr := file.Close()
		if writeErr != nil || syncErr != nil || closeErr != nil {
			return fmt.Errorf("%w: write verification bundle", ErrUnsafePath)
		}
	}
	return nil
}

// VerifyCached revalidates a persisted package and its descriptor, signature,
// and verification keyset. It never trusts the extracted cache files.
func VerifyCached(root string) (Verified, error) {
	descriptor, err := readRegularBundleFile(filepath.Join(root, "release-descriptor.json"), MaxManifestBytes)
	if err != nil {
		return Verified{}, err
	}
	signature, err := readRegularBundleFile(filepath.Join(root, "release-descriptor.sig"), 256)
	if err != nil {
		return Verified{}, err
	}
	keyset, err := readRegularBundleFile(filepath.Join(root, "verification-keyset.json"), MaxManifestBytes)
	if err != nil {
		return Verified{}, err
	}
	if !bytes.Equal(keyset, trustedKeysetRaw) {
		return Verified{}, fmt.Errorf("%w: cached trust root differs", ErrSigningKeyInvalid)
	}
	return Verify(filepath.Join(root, "package.cskin"), descriptor, signature)
}

func readRegularBundleFile(target string, limit int64) ([]byte, error) {
	info, err := os.Lstat(target)
	if err != nil {
		return nil, fmt.Errorf("%w: inspect verification bundle: %v", ErrPackageInvalid, err)
	}
	if !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 || info.Size() < 1 || info.Size() > limit {
		return nil, fmt.Errorf("%w: verification bundle file shape", ErrPackageInvalid)
	}
	file, err := os.Open(target)
	if err != nil {
		return nil, fmt.Errorf("%w: open verification bundle: %v", ErrPackageInvalid, err)
	}
	defer file.Close()
	content, err := io.ReadAll(io.LimitReader(file, limit+1))
	if err != nil || int64(len(content)) != info.Size() {
		return nil, fmt.Errorf("%w: read verification bundle", ErrPackageInvalid)
	}
	return content, nil
}

func Extract(verified Verified, destination string) error {
	if err := rejectDestination(destination); err != nil {
		return err
	}
	if err := os.Mkdir(destination, 0o700); err != nil {
		return fmt.Errorf("%w: create staging: %v", ErrUnsafePath, err)
	}
	cleanup := true
	defer func() {
		if cleanup {
			_ = os.RemoveAll(destination)
		}
	}()
	if len(verified.packageBytes) < 1 ||
		int64(len(verified.packageBytes)) != verified.PackageByteSize ||
		sha256Hex(verified.packageBytes) != verified.PackageSHA256 {
		return fmt.Errorf("%w: verified package bytes", ErrPackageInvalid)
	}
	archive, err := zip.NewReader(bytes.NewReader(verified.packageBytes), int64(len(verified.packageBytes)))
	if err != nil {
		return fmt.Errorf("%w: reopen: %v", ErrPackageInvalid, err)
	}
	names := make([]string, 0, len(archive.File))
	for _, entry := range archive.File {
		names = append(names, entry.Name)
	}
	sort.Strings(names)
	for _, name := range names {
		reader, err := archive.Open(name)
		if err != nil {
			return fmt.Errorf("%w: open entry: %v", ErrPackageInvalid, err)
		}
		target := filepath.Join(destination, filepath.FromSlash(name))
		if err := ensureContained(destination, target); err != nil {
			reader.Close()
			return err
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o700); err != nil {
			reader.Close()
			return fmt.Errorf("%w: create directory: %v", ErrUnsafePath, err)
		}
		file, err := os.OpenFile(target, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o600)
		if err != nil {
			reader.Close()
			return fmt.Errorf("%w: create file: %v", ErrUnsafePath, err)
		}
		_, copyErr := io.Copy(file, io.LimitReader(reader, MaxAssetBytes+1))
		syncErr := file.Sync()
		closeErr := file.Close()
		readerErr := reader.Close()
		if copyErr != nil || syncErr != nil || closeErr != nil || readerErr != nil {
			return fmt.Errorf("%w: write staged file", ErrUnsafePath)
		}
	}
	cleanup = false
	return nil
}

func rejectDestination(destination string) error {
	info, err := os.Lstat(destination)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("%w: inspect destination: %v", ErrUnsafePath, err)
	}
	return fmt.Errorf("%w: destination already exists (%s)", ErrUnsafePath, info.Mode())
}

func ensureContained(root, candidate string) error {
	relative, err := filepath.Rel(root, candidate)
	if err != nil || relative == "." || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) || filepath.IsAbs(relative) {
		return ErrUnsafePath
	}
	return nil
}
