# Generated by tools/render_bootstrap_pins.py; do not edit by hand.
bootstrap_release_tag='helper-v0.1.0-paid-alpha.1'
bootstrap_version='0.1.0-paid-alpha'
bootstrap_build_commit='d9ec033f34d187667091b93231852ca635bdd7eb'
bootstrap_built_at='2026-08-03T12:18:53+08:00'
case "$(uname -m)" in
  arm64)
    bootstrap_filename='codex-skin-bootstrap_0.1.0-paid-alpha_macos_arm64'
    bootstrap_sha256='59ee02d5c23a9c14fdb90a7cc6552b02ee26bc812e73f6785c773fc8ac8bc5bc'
    ;;
  x86_64)
    bootstrap_filename='codex-skin-bootstrap_0.1.0-paid-alpha_macos_x64'
    bootstrap_sha256='93f71bf6eda066002f4cff4f3c0c3859935fccfabdb74dea4f260be06ea0c00b'
    ;;
  *)
    echo "Codex Skin Bootstrap does not support this macOS architecture." >&2
    exit 50
    ;;
esac
