# Generated by tools/render_bootstrap_pins.py; do not edit by hand.
bootstrap_release_tag='helper-v0.1.0-paid-alpha.7'
bootstrap_version='0.1.0-paid-alpha.6'
bootstrap_build_commit='d8f0578d0e6684e9cc01d2d106ec7504343d05e1'
bootstrap_built_at='2026-08-05T21:55:03+08:00'
case "$(uname -m)" in
  arm64)
    bootstrap_filename='codex-skin-bootstrap_0.1.0-paid-alpha.6_macos_arm64'
    bootstrap_sha256='d8d9e439450d59d4fe1d1c69aca21caf8c8e09a7db58d7c57ea490c2a2d77251'
    ;;
  x86_64)
    bootstrap_filename='codex-skin-bootstrap_0.1.0-paid-alpha.6_macos_x64'
    bootstrap_sha256='0dfd84529794a83f6dcb882b7d3fe9f972b8ccd5cf358c7d45bd261901c48479'
    ;;
  *)
    echo "Codex Skin Bootstrap does not support this macOS architecture." >&2
    exit 50
    ;;
esac
