# Generated by tools/render_bootstrap_pins.py; do not edit by hand.
$bootstrapReleaseTag = "helper-v0.1.0-paid-alpha.2"
$bootstrapVersion = "0.1.0-paid-alpha.1"
$bootstrapBuildCommit = "239eb069d3990a9a1383f1871d5064467ecb8430"
$bootstrapBuiltAt = "2026-08-03T13:07:40+08:00"
$bootstrapFilename = "codex-skin-bootstrap_0.1.0-paid-alpha.1_windows_x64.exe"
$bootstrapSHA256 = "f3b3cd102418d6d947f39f7bcdfe38bdbd946a1219e3befaa85cdb9c92193545"
