# Generated by tools/render_bootstrap_pins.py; do not edit by hand.
$bootstrapReleaseTag = "helper-v0.1.0-paid-alpha.4"
$bootstrapVersion = "0.1.0-paid-alpha.3"
$bootstrapBuildCommit = "5780392be05dd7940b2f8852e2cd65874722722d"
$bootstrapBuiltAt = "2026-08-04T21:28:05+08:00"
$bootstrapFilename = "codex-skin-bootstrap_0.1.0-paid-alpha.3_windows_x64.exe"
$bootstrapSHA256 = "a3d5febb306128fde4f263a78c6ef6eab2e853a65fcd48381b6bbab93cbcde79"
