# Generated by tools/render_bootstrap_pins.py; do not edit by hand.
$bootstrapReleaseTag = "helper-v0.1.0-paid-alpha.14"
$bootstrapVersion = "0.1.0-paid-alpha.13"
$bootstrapBuildCommit = "c106e3082309dc33d97f9b5f7fa239e42b64cf90"
$bootstrapBuiltAt = "2026-08-21T15:56:09+08:00"
$bootstrapFilename = "codex-skin-bootstrap_0.1.0-paid-alpha.13_windows_x64.exe"
$bootstrapSHA256 = "0c000aaaea369c7ebdf28a75fb73f646d1a53d08d3b61d887fb0e51029049d9c"
