# Generated by tools/render_bootstrap_pins.py; do not edit by hand.
bootstrap_release_tag='helper-v0.1.0-paid-alpha.12'
bootstrap_version='0.1.0-paid-alpha.11'
bootstrap_build_commit='84dae0bdb6bdcda87d270dbfccaab4d4f5c7254a'
bootstrap_built_at='2026-08-20T15:48:48+08:00'
case "$(uname -m)" in
  arm64)
    bootstrap_filename='codex-skin-bootstrap_0.1.0-paid-alpha.11_macos_arm64'
    bootstrap_sha256='9480a14912be0eca11c9190b13c0aa8cb83361ebb8c178ae7ad76fc217ae6f74'
    ;;
  x86_64)
    bootstrap_filename='codex-skin-bootstrap_0.1.0-paid-alpha.11_macos_x64'
    bootstrap_sha256='0eda722a5218ce161c795c91e44ed99df0637642123323ceb25f593319ddf5b7'
    ;;
  *)
    echo "Codex Skin Bootstrap does not support this macOS architecture." >&2
    exit 50
    ;;
esac
