#!/usr/bin/env python3
"""Render fixed Plugin launcher pins from a deterministic Bootstrap build summary."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SUMMARY = ROOT / "dist" / "bootstrap" / "build-summary.json"
SHELL_OUTPUT = ROOT / "plugins" / "codex-skin" / "scripts" / "bootstrap-pins.sh"
POWERSHELL_OUTPUT = ROOT / "plugins" / "codex-skin" / "scripts" / "bootstrap-pins.ps1"
VERSION = "0.1.0-paid-alpha.1"
RELEASE_TAG = "helper-v0.1.0-paid-alpha.2"
DIGEST = re.compile(r"^[0-9a-f]{64}$")
EXPECTED = {
    "macos-arm64": f"codex-skin-bootstrap_{VERSION}_macos_arm64",
    "macos-x64": f"codex-skin-bootstrap_{VERSION}_macos_x64",
    "windows-x64": f"codex-skin-bootstrap_{VERSION}_windows_x64.exe",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--summary", type=Path, default=DEFAULT_SUMMARY)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def atomic_write(path: Path, content: str) -> None:
    encoded = content.encode()
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as handle:
        temporary = Path(handle.name)
        handle.write(encoded)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary, path)


def load(summary_path: Path) -> dict[str, dict[str, object]]:
    payload = json.loads(summary_path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict) or set(payload) != {"schemaVersion", "artifacts"} or payload["schemaVersion"] != 1:
        raise ValueError("Bootstrap build summary must use the exact schemaVersion 1 shape")
    artifacts = payload["artifacts"]
    if not isinstance(artifacts, list) or len(artifacts) != 3:
        raise ValueError("Bootstrap build summary must contain exactly three artifacts")
    result: dict[str, dict[str, object]] = {}
    for item in artifacts:
        if not isinstance(item, dict):
            raise ValueError("Bootstrap artifact must be an object")
        platform = item.get("platform")
        if platform not in EXPECTED or platform in result:
            raise ValueError("Bootstrap artifact platform set is invalid")
        if item.get("filename") != EXPECTED[platform] or item.get("bootstrapVersion") != VERSION or item.get("helperReleaseTag") != RELEASE_TAG:
            raise ValueError("Bootstrap artifact does not match the fixed Paid Alpha contract")
        digest = item.get("sha256")
        size = item.get("size")
        if not isinstance(digest, str) or DIGEST.fullmatch(digest) is None or not isinstance(size, int) or isinstance(size, bool) or size < 1:
            raise ValueError("Bootstrap artifact hash or size is invalid")
        result[platform] = item
    if set(result) != set(EXPECTED):
        raise ValueError("Bootstrap artifact platform set is incomplete")
    return result


def main() -> int:
    args = parse_args()
    artifacts = load(args.summary)
    arm = artifacts["macos-arm64"]
    x64 = artifacts["macos-x64"]
    windows = artifacts["windows-x64"]
    build_commit = arm.get("buildCommit")
    built_at = arm.get("builtAt")
    if (
        not isinstance(build_commit, str)
        or not build_commit
        or any(item.get("buildCommit") != build_commit for item in artifacts.values())
        or not isinstance(built_at, str)
        or not built_at
        or any(item.get("builtAt") != built_at for item in artifacts.values())
    ):
        raise ValueError("Bootstrap artifacts must share exact build provenance")
    shell = f"""# Generated by tools/render_bootstrap_pins.py; do not edit by hand.
bootstrap_release_tag='{RELEASE_TAG}'
bootstrap_version='{VERSION}'
bootstrap_build_commit='{build_commit}'
bootstrap_built_at='{built_at}'
case \"$(uname -m)\" in
  arm64)
    bootstrap_filename='{arm['filename']}'
    bootstrap_sha256='{arm['sha256']}'
    ;;
  x86_64)
    bootstrap_filename='{x64['filename']}'
    bootstrap_sha256='{x64['sha256']}'
    ;;
  *)
    echo \"Codex Skin Bootstrap does not support this macOS architecture.\" >&2
    exit 50
    ;;
esac
"""
    powershell = f"""# Generated by tools/render_bootstrap_pins.py; do not edit by hand.
$bootstrapReleaseTag = \"{RELEASE_TAG}\"
$bootstrapVersion = \"{VERSION}\"
$bootstrapBuildCommit = \"{build_commit}\"
$bootstrapBuiltAt = \"{built_at}\"
$bootstrapFilename = \"{windows['filename']}\"
$bootstrapSHA256 = \"{windows['sha256']}\"
"""
    if args.check:
        stale = []
        for path, expected in ((SHELL_OUTPUT, shell), (POWERSHELL_OUTPUT, powershell)):
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                stale.append(path.relative_to(ROOT).as_posix())
        if stale:
            raise ValueError("stale Bootstrap pins: " + ", ".join(stale))
    else:
        atomic_write(SHELL_OUTPUT, shell)
        atomic_write(POWERSHELL_OUTPUT, powershell)
    print("Rendered fixed Bootstrap launcher pins for macOS arm64/x64 and Windows x64.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"Bootstrap pin rendering failed: {exc}", file=sys.stderr)
        sys.exit(1)
